In [1]:
import pandas as pd


bridge = pd.read_csv("bases_atv_dev_2/bridge_movie_person.csv", nrows=20)
bridge

,sk_movie_id,sk_person_id
0,aeaa39e5a5aaf5ed549d66015e79f5ab0ec8597ce5992b...,34804511568de2626dc0316016c59db9686690e9b5ec60...
1,af3850ad62f1372fca11335a346805439cca808ecf06f2...,8cc7024d5ffdf994a8106f161493a83b5025278cd0ac50...
2,4762d8543e630ec5e6d542ca11cd750e5f08e6cf8e1842...,cbe46f077649e1de6aa5e3a3d101007882afc361ecf95e...
3,c859a293be1941182a87d333bd9f40487e63085929112f...,27477e043a5c0523839d66b2e15f40053be955763b0c2e...
4,c305eab58f997cff27e7cd707acd7c411718cf0990ec73...,b398a4d0977e678d526312d48d7c657eb8d63a7347ae10...
5,d7af0fdbcd755ca6a69c491b61c3190e9149e84549107b...,5c9a7bcb00a21510cc6153d4d2166e9f076a13fedd4fd0...
6,08e1d813fcf9e84909250b13425ce2bbdfa8f88a80e847...,34772e3ff3ef1108ac3d2f68708623fe9205880035898f...
7,c4e9a83433d9c64a45bdf3eba06a8f6c5748640e2e8e62...,cf0fa2cede26c55d20e71437f56f6cfc0eb0f6aa40bc4d...
8,c4e9a83433d9c64a45bdf3eba06a8f6c5748640e2e8e62...,bf5e0ac295b6fb1fa19ceb03263420e75b793f0a060116...
9,1573b9b439a1f7c933f6a2539e69a5afd4738efc736b65...,1aa09cda239731a8e93acdbec2259a3ada28f463d02b44...
10,3c944d81b5d760f6b857a374d8b346edafa996b99bcd65...,9da7cc2ed0321af317c031340211f5ac09848ff914bddc...
11,f0c8bbb70764bbcee46cc622717a7a5b3ebbe420bb2dec...,733b8fc18923eb426c532fe3fba26e127d86db0ad720ba...
12,ac233849104cba1dfbb1a384534b35564c646637762525...,9823f3d055108f98862e0c9f9f7b5f465cfb54bfb293c6...
13,b9353a7e15aa80d371fa0addca78fa8ca240d01294ef5a...,a6ba268f8f75f4e23a8e9ffa6de2a762c8b9a0ba2fe244...
14,8bf7b0555e81d9e7adf0d3913de1fcfdf1fbe2c7fb7d5c...,8c1b0aaa191940a70bc7e4d8a796e796b71a555c3a872d...
15,5e91746d5424477abcb5345e0c9f0dd402c115daf1d49a...,23bed4c8a1229ae1a9b18a0a9405d27ff1624165e2481e...
16,82ecd1cd606182ad72edd9f68d406acc886c7a51b900ce...,0ac047a4ba60ca4a7e90b42c9f47a07f99f9336996810d...
17,5c1fd0a20e6f576eec76b0f91dc0c93a4cf1f421277cae...,a7cbc76b159a7e259ebdd905089610b7c050be083d475f...
18,16cd1ceddd39cf268cd8a6eabaaa349946b66b7c742d4d...,c3adc53e04298fe1a807cb0f7fadddb69c4c58270fa78b...
19,fe0ddfd882e91b14312753b1c795d553f71b64e63342b1...,49cddf9c90c501b73744c7c5f42839d103363370128a06...

In [2]:
# Opcional: troca os IDs pelos nomes, para conferir a ligação filme <-> pessoa
people = pd.read_csv("bases_atv_dev1/dim_people.csv")
movies = pd.read_csv("bases_atv_dev1/dim_movies.csv", usecols=["sk_movie_id", "titulo", "ano_lancamento"])

(
    bridge
    .merge(movies, on="sk_movie_id", how="left")
    .merge(people, on="sk_person_id", how="left")
    [["titulo", "ano_lancamento", "nome_pessoa", "tipo_pessoa"]]
)

,titulo,ano_lancamento,nome_pessoa,tipo_pessoa
0,Voyage Of Time: Life's Journey,2017,Yagazie Emezi,Ator
1,Star Trek Beyond,2016,John Cho,Ator
2,The Family Fang,2016,Maryann Plunkett,Ator
3,Acapulco La Vida Va,2017,Patricio Castillo,Ator
4,Jimmy Vestvood: Amerikan Hero,2016,Sam Golzari,Ator
5,The Lost City Of Z,2017,Franco Nero,Ator
6,Damascus Cover,2017,Igal Naor,Ator
7,The Lego Batman Movie,2017,Will Arnett,Ator
8,The Lego Batman Movie,2017,Billy Dee Williams,Ator
9,Tomorrow,2019,Will Tudor,Ator
10,Incidente Em Antares - O Filme,2018,Marília Pêra,Ator
11,The Magnificent Seven,2016,Manuel Garcia-rulfo,Ator
12,American Made,2017,Domhnall Gleeson,Ator
13,The Layover,2017,Molly Shannon,Ator
14,A Cure For Wellness,2017,Ashok Mandanna,Ator
15,Final Portrait,2017,Armie Hammer,Ator
16,On The Horizon,2016,Caroline Tillette,Ator
17,Neon,2016,Alan Hess,Ator
18,Wildling,2018,Brad Dourif,Ator
19,Natural Selection,2016,Esther Zynn,Ator